app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('bestsellers/', views.bestsellers, name='bestsellers'),
    path('new/', views.new, name='new'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    # path('product/<int:product_id>/', views.product, name='product'),
    path('product/<slug:product_slug>/', views.product, name='product')
]

main/urls.py
from django.urls import path

from main import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('sales/', views.sales, name='sales'),
    path('else/', views.else_, name='else'),
    # path('contact/', views.handle_contact_form, name='contact'),  # Обработчик формы обратной связи

]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
    path('qr_code/<int:order_id>/', views.qr_code, name='qr_code'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

class OrderitemQueryset(models.QuerySet):
    
    def full_price(self):
        return sum(cart.full_price() for cart in self)
    
    def full_discount(self):
        return sum(cart.full_discount() for cart in self)

    def total_price(self):
        return sum(cart.products_price() for cart in self)


class Order(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя получателя', blank=True, null=True, default=None)
    last_name = models.CharField(max_length=150, verbose_name='Фамилия получателя', blank=True, null=True, default=None)
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    flat = models.CharField(null=True, blank=True, verbose_name='Квартира или офис')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий к заказу')
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    qr_image = models.ImageField(upload_to='qr_codes/', null=True, blank=True, verbose_name="QR-код")  # Новое поле для QR-кода
    tracking_number = models.CharField(null=True, blank=True, verbose_name='Трек-код')

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        if self.first_name and self.last_name:
            return f"Заказ № {self.pk} | Получатель {self.first_name} {self.last_name}"
        else:
            return f"Заказ № {self.pk} | Получатель {self.user.first_name} {self.user.last_name}"

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название", default=None)
    author_name = models.CharField(max_length=150, verbose_name='Автор', null=True, blank=True)
    image = models.ImageField(blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Цена", default=0)
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    # def full_price(self):
    #     return self.price * self.quantity
    
    # def full_discount(self):
    #     return  round((self.price * self.product.discount // 100), 2) * self.quantity
    
    def products_price(self):
        return round(self.price * self.quantity, 0)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

orders/forms.py
import re
from django import forms
from django.template.defaulttags import comment

# from distutils.command.clean import clean


class CreateOrderForm(forms.Form):

    first_name = forms.CharField()
    last_name = forms.CharField()
    email = forms.CharField(required=False)
    phone_number = forms.CharField()
    delivery_address = forms.CharField()
    flat = forms.CharField(required=False)
    comment = forms.CharField(required=False)
    # payment_on_get = forms.ChoiceField(choices=[('0', 'False'),
                                                # ('1', 'True'),],)

    def clean_phone_number(self):
        phone_number = self.cleaned_data['phone_number']
        # Удалите все символы, кроме цифр, из номера телефона
        cleaned_phone_number = re.sub(r'\D', '', phone_number)
        pattern = re.compile(r'^\d{11}$')
        if not pattern.match(cleaned_phone_number):
            raise forms.ValidationError("Неверный формат номера телефона")

        return cleaned_phone_number

orders/views.py
from email.mime import image
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect, render
import qrcode

from io import BytesIO
from django.core.files.base import ContentFile
from django.urls import reverse

from carts.models import Cart

from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem

from carts.utils import get_user_carts
from main.forms import ContactForm
from django.contrib import messages

from django.core.mail import send_mail


@login_required
def create_order(request):
    initial = {
            'first_name': request.user.first_name,
            'last_name': request.user.last_name,
            'email': request.user.username,
            'phone_number': request.user.phone_number
            }

    form = CreateOrderForm(initial=initial)
    modal_form = ContactForm()
    redirect_anchor = None

    if request.method == 'POST':
        form_type = request.POST.get('form_type')
        
        if form_type == 'contact_form':
            modal_form = ContactForm(request.POST)
            redirect_anchor = '#contacts'
            
            if modal_form.is_valid():
                fisrt_name = modal_form.cleaned_data['first_name']
                username = modal_form.cleaned_data['username']
                message = modal_form.cleaned_data['message']
                send_contact_email(fisrt_name, username, message)
                messages.success(request, "Сообщение успешно отправлено!")
            else:
                errors = {field: error for field, error in modal_form.errors.items()}
                messages.error(request, "Ошибка при отправке сообщения")
        
        elif form_type == 'profile_form':
            form = CreateOrderForm(data=request.POST)
        if form.is_valid():
            try:
                with transaction.atomic():  # Обеспечение атомарности операции
                    user = request.user
                    cart_items = Cart.objects.filter(user=user)

                    if not cart_items.exists():
                        messages.warning(request, "Ваша корзина пуста.")
                        return redirect("goods:catalog")

                    # Создание заказа
                    order = Order.objects.create(
                        user=user,
                        first_name = form.cleaned_data['first_name'],
                        last_name = form.cleaned_data['last_name'],
                        phone_number=form.cleaned_data['phone_number'],
                        delivery_address=form.cleaned_data['delivery_address'],
                        flat=form.cleaned_data.get('flat', None),
                        # payment_on_get=form.cleaned_data['payment_on_get'],
                        comment=form.cleaned_data.get('comment', None),
                    )

                    total_amount = 0  # Общая сумма заказа

                    # Создание заказанных товаров
                    for cart_item in cart_items:
                        product = cart_item.product
                        name = cart_item.product.name
                        author_name = cart_item.product.author_name
                        image = cart_item.product.image
                        price = cart_item.product.sell_price()
                        quantity = cart_item.quantity

                        if product.quantity < quantity:
                            raise ValidationError(f"Недостаточно товара {name}. В наличии - {product.quantity}")

                        # Создание `OrderItem` для каждого товара в корзине
                        OrderItem.objects.create(
                            order=order,
                            product=product,
                            author_name=author_name,
                            name=name,
                            image = image,
                            price=price,
                            quantity=quantity,
                        )

                        product.quantity -= quantity  # Уменьшение количества товара
                        product.save()  # Сохранение изменений в базе данных

                        total_amount += price * quantity  # Добавление к общей сумме

                    # Генерация QR-кода
                    total_amount_in_cents = int(total_amount * 100)

                    qr_data = (
                        f"ST00012|Name=ИП Чумакова О.Р.|PersonalAcc=40817810600089220095|"
                        f"BankName=Тинькофф Банк|BIC=044525974|CorrespAcc=30101810145250000974|"
                        f"Currency=RUB|Sum={total_amount_in_cents}|Purpose=Оплата заказа Chapter & Verse"
                    )

                    buffer = BytesIO()
                    qr = qrcode.make(qr_data)
                    qr.save(buffer, format="PNG")

                    qr_image_file = ContentFile(buffer.getvalue(), 'qr_code.png')  # Создание файла
                    order.qr_image.save('qr_code.png', qr_image_file, save=True)

                    cart_items.delete()  # Очистка корзины после заказа

                    # Перенаправление на страницу с QR-кодом
                    return redirect(reverse("orders:qr_code", kwargs={'order_id': order.id})) 

            except ValidationError as e:
                messages.warning(request, str(e))
                return redirect("user:users_cart")

    carts = get_user_carts(request)
    total_price = sum(cart.full_price() for cart in carts)
    total_discount = sum(cart.full_discount() for cart in carts)
    total_price_with_discount = total_price - total_discount
    
    context = {
        'carts': carts,
        'total_price': total_price,
        'total_discount': total_discount,
        'total_price_with_discount': total_price_with_discount,
        'title': 'Chapter & Verse - Оформление заказа',
        'form': form,
        'orders': True,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
    }
    return render(request, 'orders/create_order.html', context)

# def order(request):
#     if request.method == 'POST':
#         form = CreateOrderForm(data=request.POST)
#         if form.is_valid():
#             try:
#                 with transaction.atomic():  # Обеспечение атомарности операции
#                     user = request.user
#                     cart_items = Cart.objects.filter(user=user)

#                     if not cart_items.exists():
#                         messages.warning(request, "Ваша корзина пуста.")
#                         return redirect("goods:catalog")

#                     # Создание заказа
#                     order = Order.objects.create(
#                         user=user,
#                         first_name = form.cleaned_data['first_name'],
#                         last_name = form.cleaned_data['last_name'],
#                         phone_number=form.cleaned_data['phone_number'],
#                         delivery_address=form.cleaned_data['delivery_address'],
#                         flat=form.cleaned_data.get('flat', None),
#                         # payment_on_get=form.cleaned_data['payment_on_get'],
#                         comment=form.cleaned_data.get('comment', None),
#                     )

#                     total_amount = 0  # Общая сумма заказа

#                     # Создание заказанных товаров
#                     for cart_item in cart_items:
#                         product = cart_item.product
#                         name = cart_item.product.name
#                         author_name = cart_item.product.author_name
#                         price = cart_item.product.sell_price()
#                         quantity = cart_item.quantity

#                         if product.quantity < quantity:
#                             raise ValidationError(f"Недостаточно товара {name}. В наличии - {product.quantity}")

#                         # Создание `OrderItem` для каждого товара в корзине
#                         OrderItem.objects.create(
#                             order=order,
#                             product=product,
#                             author_name=author_name,
#                             name=name,
#                             price=price,
#                             quantity=quantity,
#                         )

#                         product.quantity -= quantity  # Уменьшение количества товара
#                         product.save()  # Сохранение изменений в базе данных

#                         total_amount += price * quantity  # Добавление к общей сумме

#                     # # Генерация QR-кода
#                     # total_amount_in_cents = int(total_amount * 100)

#                     # qr_data = (
#                     #     f"ST00012|Name=Спорт Лайн|PersonalAcc=40817810711524044721|"
#                     #     f"BankName=ВТБ|BIC=043601968|CorrespAcc=30101810422023601968|"
#                     #     f"Currency=RUB|Sum={total_amount_in_cents}|Purpose=Оплата заказа №{order.id}"
#                     # )

#                     # buffer = BytesIO()
#                     # qr = qrcode.make(qr_data)
#                     # qr.save(buffer, format="PNG")

#                     # qr_image_file = ContentFile(buffer.getvalue(), 'qr_code.png')  # Создание файла
#                     # order.qr_image.save('qr_code.png', qr_image_file, save=True)

#                     cart_items.delete()  # Очистка корзины после заказа

#                     # messages.success(request, "Заказ успешно оформлен!")  # Уведомление

#                     # # Перенаправление на страницу с QR-кодом
#                     # return redirect(reverse("orders:qr_code", kwargs={'order_id': order.id}))
#                     return redirect('user:profile')  

#             except ValidationError as e:
#                 messages.warning(request, str(e))

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% load custom_filters %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\order registration.css" %}">
{% endblock css %}


{% block content %}
    <section class="panel">
        <ul class="menu">
            <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
                <b>Акции</b>
            </li></a>
            <li class="menu_catalog">
                <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
                <ul class="sub-menu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
                    {% endfor %}
                </ul>
            </li>
            <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
                <b>Что еще почитать?</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:bestsellers" %}"><li class="menu_item">
                <b>Бестселлеры</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:new" %}"><li class="menu_item">
                <b>Новинки</b>
            </li></a>
            <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
                <b>О нас</b>
            </li></a>
        </ul>
    </section>

    <hr>

    <section class="block">
        <div class="block__title">
            <b>Оформление заказа</b>
        </div>
        <form action="{% url "orders:create_order" %}" method='post'>
            {% csrf_token %}
            <input type="hidden" name="form_type" value="profile_form">
            <div class="block__main">
                <div class="block__main_item">
                    <div class="step">
                        <div class="step__title">
                            <b>Получатель</b>
                        </div>
                        <div class="step__block main__item">
                            <div class="main__item_inputContainer">
                                <input class="main__item_inputContainer-txt" 
                                inputmode="kana-name" 
                                placeholder="*Имя" required 
                                type="name" 
                                value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" 
                                name="first_name" 
                                id='id_first_name'>
                            </div>
                            {% if form.first_name.errors %}
                            <div class="alert-danger">
                                {{form.first_name.errors}}
                            </div>
                            {% endif %}
                            <div class="main__item_inputContainer">
                                <input class="main__item_inputContainer-txt" 
                                inputmode="surname" 
                                placeholder="*Фамилия" required 
                                type="surname" 
                                value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" 
                                name="last_name" 
                                id='id_last_name'>
                            </div>
                            {% if form.last_name.errors %}
                            <div class="alert-danger">
                                {{form.last_name.errors}}
                            </div>
                            {% endif %}
                            <div class="main__item_inputContainer">
                                <input class="main__item_inputContainer-txt"
                                placeholder="*Телефон" required 
                                type="tel" 
                                value="{% if form.phone_number.value %}{{form.phone_number.value|phone_format}}{% endif %}" 
                                name="phone_number" id='id_phone_number'>
                            </div>
                            {% if form.phone_number.errors %}
                            <div class="alert-danger">
                            {{form.phone_number.errors}}
                            </div>
                            {% endif %}
                            <div class="main__item_inputContainer">
                                <input class="main__item_inputContainer-txt" 
                                placeholder="email"
                                type="email" 
                                value="{{form.username.value}}" 
                                name="username" 
                                id='id_username'>
                            </div>
                            {% if form.username.errors %}
                            <div class="alert-danger">
                                {{form.username.errors}}
                            </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="step">
                        <div class="step__title">
                            <b>Доставка</b>
                        </div>
                        <div class="step__block">
                            <p style="font-size: 18px; text-decoration: underline 0.5px;">Область доставки - <b>г. Саратов</b></p>
                            <p style="font-size: 18px; text-decoration: underline 0.5px;">Тип доставки - <b>Курьер</b></p>
                            <p style="font-size: 20px; margin-top: 3%; margin-bottom: 1%;"><b>Куда доставить?</b></p>
                            <div class="main__item_title">
                                Улица и номер дома
                            </div>
                            <div class="main__item_inputContainer" style="width: 45%;">
                                <input class="main__item_inputContainer-txt" 
                                placeholder="Невский проспект, 51/53, к. 3, стр. 2, лит. А" 
                                type="text" tabindex="0" 
                                name="delivery_address" 
                                id='id_delivery_address' required="required" 
                                autocomplete="street-address address-line1"
                                value="{% if form.delivery_address.value %}{{ form.delivery_address.value }}{% endif %}">
                            </div>
                            {% if form.delivery_address.errors %}
                                <div class="alert-danger">{{form.delivery_address.errors}}</div>
                            {% endif %}
                            <div class="step__block main__item" style="grid-template-columns: 1fr 3fr;">
                                <div class="main__item_block">
                                    <div class="main__item_title">
                                        Квартира или офис
                                    </div>
                                    <div class="main__item_inputContainer" style="width: 55%;">
                                        <input class="main__item_inputContainer-txt" 
                                        type="text" 
                                        placeholder="570" tabindex="0" 
                                        name="flat" 
                                        id='id_flat' 
                                        autocomplete="street-address address-line3"
                                        value="{% if form.flat.value %}{{ form.flat.value }}{% endif %}">
                                    </div>
                                    {% if form.flat.errors %}
                                        <div class="alert-danger">{{form.flat.errors}}</div>
                                    {% endif %}
                                </div>
                                <div class="main__item_block">
                                    <div class="main__item_title">
                                        Комментарий курьеру
                                    </div>
                                    <div class="main__item_inputContainer" style="width: 86%;">
                                        <input class="main__item_inputContainer-txt" 
                                        type="text" 
                                        placeholder="Как пройти, откуда вход — всё, что поможет доставить заказ" 
                                        tabindex="0" 
                                        maxlength="250" 
                                        name="comment" 
                                        id='id_comment' wfd-id="id4">
                                    </div>
                                    {% if form.comment.errors %}
                                        <div class="alert-danger">{{form.comment.errors}}</div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="block__main_pay">
                    <div class="sum">
                        <div class="sum__item">
                            <div class="sum__item_title">
                                Сумма заказа
                            </div>
                            <div class="sum__item_value">
                                {{total_price}} ₽
                            </div>
                        </div>
                        <div class="sum__item">
                            <div class="sum__item_title">
                                Скидка
                            </div>
                            <div class="sum__item_value">
                                {{total_discount}} ₽
                            </div>
                        </div>
                        <div class="sum__item">
                            <div class="sum__item_title">
                                <b>Итого</b>
                            </div>
                            <div class="sum__item_value">
                                <b>{{total_price_with_discount }} ₽</b>
                            </div>
                        </div>
                    </div>
                    <div class="block__main_pay-btn">
                        <button href="" type="submit" class="block__main_pay-btn">Оформить заказ</button>
                    </div>
                </div>
            </div>
        </form>
    </section>

{% endblock %}

orders/templates/orders/qr_code.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% load custom_filters %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\order registration.css" %}">
{% endblock css %}


{% block content %}
    <section class="panel">
        <ul class="menu">
            <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
                <b>Акции</b>
            </li></a>
            <li class="menu_catalog">
                <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
                <ul class="sub-menu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
                    {% endfor %}
                </ul>
            </li>
            <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
                <b>Что еще почитать?</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:bestsellers" %}"><li class="menu_item">
                <b>Бестселлеры</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:new" %}"><li class="menu_item">
                <b>Новинки</b>
            </li></a>
            <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
                <b>О нас</b>
            </li></a>
        </ul>
    </section>

    <hr>

    <section class='qr'>
        <div class="container" style=" text-align: center; justify-content: center; display: flex;">
            <div class="row justify-content-center" style="align-items: center;/* margin-top: 50px; *//* display: flex; */font-size: 18px;">
                <h2>Оплата через QR-код</h2>  <!-- Подпись -->
                <p>Пожалуйста, используйте банковское приложение для сканирования QR-кода и оплаты вашего заказа.</p>  <!-- Инструкции -->
                {% if qr_image_url %}
                    <div style="/* border: 1px solid #ccc; *//* padding: 10px; *//* background-color: #f9f9f9; *//* border-radius: 10px; */">  <!-- Рамка -->
                        <img src="/media/qr_codes/qr_code_Idr0Grh.png" alt="QR Code" style="pointer-events: none;width: 30%;padding: 1%;/* display: flex; *//* max-width: 200px; *//* max-height: 200px; */border: 1px solid #ccc;/* padding: 10px; */background-color: #f9f9f9;border-radius: 10px;">  <!-- Уменьшение размера -->
                    </div>
                {% else %}
                    <div>QR-код не найден.</div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}