app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
    path('like_add/', views.like_add, name='like_add'),
    path('like_remove/', views.like_remove, name='like_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('bestsellers/', views.bestsellers, name='bestsellers'),
    path('new/', views.new, name='new'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    # path('product/<int:product_id>/', views.product, name='product'),
    path('product/<slug:product_slug>/', views.product, name='product')
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.create_order, name='create_order'),
    path('qr_code/<int:order_id>/', views.qr_code, name='qr_code'),
]

carts/models.py
from django.db import models
from users.models import User
from goods.models import Products

class CartQueryset(models.QuerySet):

    def full_price(self):
        return sum(cart.full_price() for cart in self)
    
    def full_discount(self):
        return sum(cart.full_discount() for cart in self)

    def total_price(self):
        return sum(cart.product_price() for cart in self)

class Cart(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    quantity = models.PositiveSmallIntegerField(default=0, verbose_name='Количество')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'cart'
        verbose_name = "Корзина"
        verbose_name_plural = "Корзина"
        ordering = ("id",)

    objects = CartQueryset().as_manager()

    def full_price(self):
        return self.product.price * self.quantity
    
    def full_discount(self):
        return  round((self.product.price * self.product.discount // 100), 2) * self.quantity
    
    def product_price(self):
        return round(self.product.sell_price() * self.quantity, 0)

    def __str__(self):
        if self.user:
            return f'Корзина {self.user.username} | Товар {self.product.name} | Количество {self.quantity}'
        
        return f'Анонимная корзина | Товар {self.product.name} | Количество {self.quantity}'
    

class Like(models.Model):

    user = models.ForeignKey(to=User, on_delete=models.CASCADE, blank=True, null=True, verbose_name='Пользователь')
    product = models.ForeignKey(to=Products, on_delete=models.CASCADE, verbose_name='Товар')
    session_key = models.CharField(max_length=32, null=True, blank=True)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')

    class Meta:
        db_table = 'like'
        verbose_name = "Избранное"
        verbose_name_plural = "Избранное"

    def __str__(self):
        if self.user:
            return f'Избранное {self.user.username} | Товар {self.product.name}'
        
        return f'Анонимное избранное | Товар {self.product.name}'

carts/views.py
from django.http import FileResponse, HttpResponse, JsonResponse
from django.shortcuts import redirect, get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse
from carts.utils import get_user_carts, get_user_likes

from carts.models import Cart, Like
from goods.models import Products

def cart_add(request):
    
    product_id = request.POST.get("product_id")

    product = Products.objects.get(id=product_id)
    
    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user, product=product)

        if carts.exists():
            cart = carts.first()
            if cart :
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(user=request.user, product=product, quantity=1)

    else:
        carts = Cart.objects.filter(
            session_key = request.session.session_key, product=product)
        
        if carts.exists():
            cart = carts.first()
            if cart:
                cart.quantity += 1
                cart.save()
        else:
            Cart.objects.create(
                session_key = request.session.session_key, product=product, quantity=1
            )    
    
    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "cart_items_html": cart_items_html
    }

    return JsonResponse(response_data)

def cart_change(request):
    cart_id = request.POST.get("cart_id")
    quantity = request.POST.get("quantity")

    cart = Cart.objects.get(id=cart_id)

    cart.quantity = quantity
    cart.save()

    cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": cart}, request=request
    )

    response_data = {
        "cart_items_html": cart_items_html,
    }

    return JsonResponse(response_data)

def cart_remove(request):
    cart_id = request.POST.get("cart_id")

    cart = Cart.objects.get(id=cart_id)
    quantity = cart.quantity
    cart.delete()

    user_cart = get_user_carts(request)
    cart_items_html = render_to_string(
        "carts/includes/included_cart.html", {"carts": user_cart}, request=request
    )

    response_data = {
        "cart_items_html": cart_items_html,
        "quantity_deleted": quantity,
    }

    return JsonResponse(response_data)

def like_add(request):
    
    product_id = request.POST.get("product_id")

    product = Products.objects.get(id=product_id)
    
    if request.user.is_authenticated:
        likes = Like.objects.filter(user=request.user, product=product)

        if likes.exists():
            like = likes.first()
            if like:
                like.save()
        else:
            Like.objects.create(user=request.user, product=product)

    else:
        likes = Like.objects.filter(
            session_key = request.session.session_key, product=product)
        
        if likes.exists():
            like = likes.first()
            if like:
                like.save()
        else:
            Like.objects.create(
                session_key = request.session.session_key, product=product
            )    
    
    user_like = get_user_likes(request)
    like_items_html = render_to_string(
        "carts/includes/included_like.html", {"likes": user_like}, request=request
    )

    response_data = {
        "like_items_html": like_items_html
    }

    return JsonResponse(response_data)

def like_remove(request):
    like_id = request.POST.get("like_id")

    like = Like.objects.get(id=like_id)
    like.delete()

    user_like = get_user_likes(request)
    like_items_html = render_to_string(
        "carts/includes/included_like.html", {"likes": user_like}, request=request
    )

    response_data = {
        "like_items_html": like_items_html,
    }

    return JsonResponse(response_data)

carts/templates/carts/includes/included_cart.html
{% load static %}

{% load carts_tags %}
{% load goods_tags %}
{% user_carts request as carts %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\shopping bag.css" %}">
{% endblock css %}

<div class="block__main">
    {% if carts %}
        <div class="block__main_goods">
            {% for cart in carts %}
                <div class="good" id="cart-item-{{ cart.id }}">
                    <div class="good__pic">
                        <a href="{% url "catalog:product" cart.product.slug %}">
                            {% if cart.product.image %}
                                <img src={{cart.product.image.url}} alt="{{cart.product.name}}">
                            {% endif %}                        
                        </a>
                    </div>
                    <div class="good__text">
                        <div class="good__text_title">
                            <div class="good__text_title-name">
                                <a href="{% url "catalog:product" cart.product.slug %}">
                                    <div class="book-title">
                                        <b>{{cart.product.name}}</b>
                                    </div>
                                    <div class="book-author">
                                        {% if cart.product.author_name %}
                                            {{cart.product.author_name}}
                                        {% else %}
                                            <br>
                                        {% endif %}
                                    </div>
                                </a>
                            </div>
                            <a class="good__text_title-cancel remove-from-cart" href="{% url "cart:cart_remove"%}" data-cart-id="{{cart.id}}">
                                {% csrf_token %}
                                <b>X</b>
                            </a>
                        </div>
                        <div class="good__text_price">
                            {% if cart.product.discount %}
                                <div class="good__text_price-old">
                                    {{cart.full_price}} ₽
                                    <svg viewBox="0 0 52 5" fill="none" xmlns="http://www.w3.org/2000/svg" class="product-price__line">
                                        <path d="M.88 3.938c16.403-3.917 33.836-3.917 50.238 0" stroke="#F34A57" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"></path>
                                    </svg>
                                </div>
                                <div class="good__text_price-new">
                                    {% if cart.quantity > 1 %}
                                        <b>{{cart.product_price}} ₽ </b>&nbsp &nbsp <span style='color: darkgrey;'>{{cart.product.sell_price}} ₽/шт </span>                                     
                                    {% else %}
                                        <b>{{cart.product_price}} ₽/шт</b>
                                    {% endif %}
                                </div>
                            {% else %}
                                <div class="good__text_price-old">
                                    <br>
                                </div>
                                <div class="good__text_price-new" style='color: black;'>
                                    {% if cart.quantity > 1 %}
                                        <b>{{cart.product_price}} ₽</b>&nbsp &nbsp <span style='color: darkgrey;'>{{cart.product.sell_price}} ₽/шт </span>                                        
                                    {% else %}
                                        <b>{{cart.product_price}} ₽/шт</b>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                        <div class="good__text_btn">
                            {% if cart.product.id in favourites %}
                                <a href="{% url "cart:like_add" %}" class="add-to-like added-to-like" data-product-id="{{cart.product.id}}">
                                    {% csrf_token %}
                                    <button class="good__text_btn-pic">
                                        <img src={% static "icons\Group.png" %}>
                                    </button>
                                </a>
                            {% else %}
                                <a href="{% url "cart:like_add" %}" class="add-to-like" data-product-id="{{cart.product.id}}">
                                    {% csrf_token %}
                                    <button class="good__text_btn-pic">
                                        <img src={% static "icons\Group.png" %}>
                                    </button>
                                </a>
                            {% endif %}
                            {% if cart.quantity >= cart.product.quantity %}
                                <div data-v-7889c1e6="" class="product-quantity cart-item__quantity-control input-group">
                                    <span class="input-group-btn">
                                        <button type='button' data-cart-id="{{cart.id}}" data-cart-change-url="{% url "cart:cart_change" %}" class="decrement product-quantity__button product-quantity__button--left product-quantity__button--disabled">
                                            {% csrf_token %}
                                            -
                                        </button> 
                                    </span>
                                    <input max='300' type="text" class="product-quantity__counter number" value="{{cart.quantity}}"> 
                                    <span class="input-group-btn">
                                        <button class=" product-quantity__button product-quantity__button--right" style='opacity: 0.4'>
                                            {% csrf_token %}
                                            +
                                        </button>
                                    </span>
                                </div>
                                <b style='color: #fdd835; margin-left: 2%;'>Осталось всего {{cart.product.quantity}}!!!</b>
                            {% else %}
                                <div data-v-7889c1e6="" class="product-quantity cart-item__quantity-control input-group">
                                    <span class="input-group-btn">
                                        <button type='button' data-cart-id="{{cart.id}}" data-cart-change-url="{% url "cart:cart_change" %}" class="decrement product-quantity__button product-quantity__button--left product-quantity__button--disabled">
                                            {% csrf_token %}
                                            -
                                        </button> 
                                    </span>
                                    <input max='300' type="text" class="product-quantity__counter number" value="{{cart.quantity}}"> 
                                    <span class="input-group-btn">
                                        <button type='button' data-cart-id="{{cart.id}}" data-cart-change-url="{% url "cart:cart_change" %}" class="increment product-quantity__button product-quantity__button--right">
                                            {% csrf_token %}
                                            +
                                        </button>
                                    </span>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="block__main_pay">
            <div class="sum">
                <div class="sum__item">
                    <div class="sum__item_title">
                        Сумма заказа
                    </div>
                    <div class="sum__item_value">
                        {{carts.full_price}} ₽
                    </div>
                </div>
                <div class="sum__item">
                    <div class="sum__item_title">
                        Скидка
                    </div>
                    <div class="sum__item_value">
                        {{carts.full_discount}} ₽
                    </div>
                </div>
                <div class="sum__item">
                    <div class="sum__item_title">
                        <b>Итого</b>
                    </div>
                    <div class="sum__item_value">
                        <b>{{carts.total_price}} ₽</b>
                    </div>
                </div>
            </div>
            <div class="block__main_pay-btn">
                <a href="{% url "orders:create_order" %}" class="block__main_pay-btn">Перейти к оформлению</a>
            </div>
        </div>
    {% else %}
        <b style='color: darkgrey; font-size: 24px;'>Вы пока ничего не выбрали :( </b>
    {% endif %}
</div>

carts/templates/carts/includes/included_like.html
{% load static %}

{% load carts_tags %}
{% load goods_tags %}
{% user_likes request as likes %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\like.css" %}">
{% endblock css %}

{% block content %}
    {% if likes %}
        <div class="main__item">
            {% for like in likes %}
                <div class="main__item_good">
                    <div class="product">
                        <a id="product" href="{% url "catalog:product" like.product.slug %}">
                            <div class="product-photo">
                                {% if like.product.image %}
                                    <img src={{like.product.image.url}} alt="{{like.product.name}}">
                                {% endif %} 
                            </div>
                            <div class="product-title">
                                <div class="product-title__head">
                                    <b>{{like.product.name}}</b>
                                </div>
                                <div class="product-title__author">
                                    {% if like.product.author_name %}
                                        {{like.product.author_name}}
                                    {% else %}
                                        <br>
                                    {% endif %}
                                </div>
                            </div>
                        </a>
                        <div class="product-info">
                            <div class="product-info__pic">
                                {% if like.product.quantity == 0 %}
                                    {% if like.product.id in basket %}
                                        <a class="add-to-cart added-to-cart">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group 43.png" %}>
                                            </button>
                                        </a>
                                    {% else %}
                                        <a class="add-to-cart">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group 43.png" %}>
                                            </button>
                                        </a>
                                    {% endif %}
                                {% else %}
                                    {% if like.product.id in basket %}
                                        <a href="{% url "cart:cart_add" %}" class="add-to-cart added-to-cart" data-product-id="{{like.product.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group 43.png" %}>
                                            </button>
                                        </a>
                                    {% else %}
                                        <a href="{% url "cart:cart_add" %}" class="add-to-cart" data-product-id="{{like.product.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group 43.png" %}>
                                            </button>
                                        </a>
                                    {% endif %}
                                {% endif %}
                                <a href="{% url "cart:like_remove" %}" class="remove-from-like added-to-like" data-like-id="{{like.id}}">
                                    {% csrf_token %}
                                    <button class="product-info__pic">
                                        <img src={% static "icons\Group.png" %}>
                                    </button>
                                </a>
                            </div>
                            <div class="product-price">
                                {% if like.product.discount %}
                                    <div class="product-price__old">
                                        {{like.product.price}} ₽
                                        <svg viewBox="0 0 52 5" fill="none" xmlns="http://www.w3.org/2000/svg" class="product-price__line">
                                            <path d="M.88 3.938c16.403-3.917 33.836-3.917 50.238 0" stroke="#F34A57" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"></path>
                                        </svg>
                                    </div>
                                    <div class="product-price__new">
                                        <b>{{like.product.sell_price}} ₽</b>
                                    </div>
                                {% else %}
                                    <div class="product-price__old">
                                        <br>
                                    </div>
                                    <div class="product-price__new" style='color: black;'>
                                        <b>{{like.product.price}} ₽</b>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <b style='color: darkgrey; font-size: 24px;'>Вы пока ничего не выбрали :( </b>
    {% endif %}
{% endblock %}