app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path

from carts import views

app_name = 'carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
    path('like_add/', views.like_add, name='like_add'),
    path('like_remove/', views.like_remove, name='like_remove'),
]

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('bestsellers/', views.bestsellers, name='bestsellers'),
    path('new/', views.new, name='new'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    # path('product/<int:product_id>/', views.product, name='product'),
    path('product/<slug:product_slug>/', views.product, name='product')
]

main/urls.py
from django.urls import path

from main import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('sales/', views.sales, name='sales'),
    path('else/', views.else_, name='else'),
    # path('contact/', views.handle_contact_form, name='contact'),  # Обработчик формы обратной связи

]

goods/models.py
from django.urls import reverse
from django.db import models

class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    class Meta:
        db_table = 'category'
        verbose_name = 'Категорию'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name 

class Products(models.Model):
    name = models.CharField(max_length=150, verbose_name='Название')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    author_name = models.CharField(max_length=150, null=True, blank=True, verbose_name='Автор')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='goods_images', blank=True, null=True, verbose_name='Изображение')
    price = models.PositiveIntegerField(default=0, max_length=6, verbose_name='Цена')
    discount = models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Количество')
    age = models.PositiveIntegerField(default=0, max_length=6, null=True, verbose_name='Возраст')
    year_of_publish = models.PositiveIntegerField(max_length=4, null=True, verbose_name='Год издания')
    publisher = models.CharField(max_length=150,null=True, verbose_name='Издательство')
    cycle = models.CharField(max_length=150, null =True, blank=True, verbose_name='Цикл')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')

    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('id', )

    def __str__(self):
        return f'{self.name} Количество - {self.quantity}'
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})
    def display_id(self):
        return f'{self.id:05}'
    def sell_price(self):
        if self.discount:
            return self.price - self.price * self.discount // 100
        return self.price

goods/views.py
from calendar import c
from django.shortcuts import get_list_or_404, render
from django.shortcuts import get_object_or_404
from datetime import datetime
from goods.models import Products
from goods.models import Categories
from goods.utils import q_search
from carts.models import Cart, Like
from main.forms import ContactForm
from django.contrib import messages
from django.core.mail import send_mail

def catalog(request, category_slug=None):
    query = request.GET.get('q', None)
    modal_form, redirect_anchor = handle_contact_form(request)

    if request.user.is_authenticated:
        basket = [item.product_id for item in Cart.objects.filter(user=request.user)]
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        basket = [item.product_id for item in Cart.objects.filter(session_key = request.session.session_key)]
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]

    if query:
        goods = q_search(query)
        category = None
    else:
        goods= get_list_or_404(Products.objects.filter(category__slug=category_slug))
        category = get_object_or_404(Categories, slug=category_slug)
            
    context = {
        'title': 'Chepter & Verse: Каталог',
        "goods": goods,
        "slug_url": category_slug,
        "current_category": category,
        'basket': basket,
        'favourites': favourites,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
    }
    return render(request, 'goods/catalog.html', context)

def product(request, product_slug=False, product_id=False):
    modal_form, redirect_anchor = handle_contact_form(request)
    if request.user.is_authenticated:
        basket = [item.product_id for item in Cart.objects.filter(user=request.user)]
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        basket = [item.product_id for item in Cart.objects.filter(session_key = request.session.session_key)]
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]

    if product_id:
        product = Products.objects.get(id=product_id)
    else:
        product = Products.objects.get(slug=product_slug)

    context = {
        'product': product,
        'basket': basket,
        'favourites': favourites,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor   
    }
    return render(request, 'goods/product.html', context=context)

def bestsellers(request):
    categories = Categories.objects.all()
    bests = Products.objects.filter(quantity__lt=5).order_by('?')[:6]
    modal_form, redirect_anchor = handle_contact_form(request)
    if request.user.is_authenticated:
        basket = [item.product_id for item in Cart.objects.filter(user=request.user)]
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        basket = [item.product_id for item in Cart.objects.filter(session_key = request.session.session_key)]
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]

    context: dict = {
        'title': 'Chapter & Verse - Бестселлеры',
        'categories': categories,
        'bests': bests,
        'basket': basket,
        'favourites': favourites,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
    }
    return render(request, 'goods/bestsellers.html', context)

def new(request):
    categories = Categories.objects.all()
    new = Products.objects.filter(year_of_publish=datetime.now().year)
    modal_form, redirect_anchor = handle_contact_form(request)

    if request.user.is_authenticated:
        basket = [item.product_id for item in Cart.objects.filter(user=request.user)]
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        basket = [item.product_id for item in Cart.objects.filter(session_key = request.session.session_key)]
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]

    context: dict = {
        'title': 'Chapter & Verse - Новинки',
        'categories': categories,
        'new': new,
        'basket': basket,
        'favourites': favourites,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
    }
    return render(request, 'goods/new.html', context)

def send_contact_email(first_name, username, message):
    subject = "Сообщение с вашего сайта"
    body = f"Сообщение от {first_name} ({username}):\n\n{message}"
    from_email = 'olechka.chumakovachumakova@yandex.ru'  # Адрес электронной почты отправителя
    to_email = 'olechka.chumakovachumakova@yandex.ru'  # Адрес электронной почты, куда придет письмо
    
    send_mail(
        subject,
        body,
        from_email, 
        [to_email], 
        fail_silently=False
    )

def handle_contact_form(request):
    if request.method == 'POST':
        modal_form = ContactForm(request.POST)
        redirect_anchor = '#contacts'
        if modal_form.is_valid():
            fisrt_name = modal_form.cleaned_data['first_name']
            username = modal_form.cleaned_data['username']
            message = modal_form.cleaned_data['message']
            send_contact_email(fisrt_name, username, message)
            messages.success(request, "Сообщение успешно отправлено!")
        else:
            errors = {field: error for field, error in modal_form.errors.items()}
            messages.error(request, "Ошибка при отправке сообщения")
    else:
        modal_form = ContactForm()  # Создаем новую форму для GET-запроса
        redirect_anchor = None
    return modal_form, redirect_anchor

goods/templates/goods/bestsellers.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\bestsellers.css" %}">
{% endblock css %}


{% block content %}
    <section class="panel">
        <ul class="menu">
            <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
                <b>Акции</b>
            </li></a>
            <li class="menu_catalog">
                <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
                <ul class="sub-menu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
                    {% endfor %}
                </ul>
            </li>
            <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
                <b>Что еще почитать?</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:bestsellers" %}" style="background-color: #fff59d; color: #000; "><li class="menu_item">
                <b>Бестселлеры</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:new" %}"><li class="menu_item">
                <b>Новинки</b>
            </li></a>
            <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
                <b>О нас</b>
            </li></a>
        </ul>
    </section>

    <hr>

    <section class="the-most-bestseller">
        <div class="bestseller">
            <div class="bestseller__text">
                <h1>Бестселлер месяца</h1>
                <p>Жить просто - значит избавиться от всего, что не приносит пользу.<br> От ненужных переживаний о прошлом и будущем, от бесконечных попыток быть всегда продуктивным и угрызений совести, если что-то идет не так.</p>
                <div class="bestseller__text_dop">
                    <p1><b>Психология счастья</b></p1>
                    <a class='adverts__pictures-slide-third--a' href="{% url "catalog:product" product_slug='iskusstvo-zaboty-o-dushe-100-insajtov-dzen-buddijskogo-monaha-o-zhizni-bez-stressa' %}"><b>Перейти</b></a>
                </div>
            </div>
            <div class="bestseller__pic">
                <img src={% static "images\main\искусство заботы о душе.png" %}>
            </div>
        </div>
    </section>

    <section class="best">
        <div class="best__title">
            <h1>Лучшие из лучших</h1>
        </div>
        <div class="best__goods">
            <ul class="products clearfix">
                {% for good in bests %}
                    <li class="product-wrapper">
                        <div class="product">
                            <a href="{% url "catalog:product" good.slug %}" id="product">
                                <div class="product-photo">
                                    {% if good.image %}
                                    <img src={{good.image.url}} alt="{{good.name}}">
                                    {% endif %}
                                </div>
                                <div class="product-title">
                                    <div class="product-title__head">
                                        <b>{{good.name}}</b>
                                    </div>
                                    <div class="product-title__author">
                                        {% if good.author_name %}
                                            {{good.author_name}}
                                        {% else %}
                                            <br>
                                        {% endif %}
                                    </div>
                                </div>
                            </a>
                            <div class="product-info">
                                <div class="product-info__pic">
                                    {% if good.quantity == 0 %}
                                        {% if good.id in basket %}
                                            <a class="add-to-cart added-to-cart">
                                                {% csrf_token %}
                                                <button class="product-info__pic">
                                                    <img src={% static "icons\Group 43.png" %}>
                                                </button>
                                            </a>
                                        {% else %}
                                            <a class="add-to-cart">
                                                {% csrf_token %}
                                                <button class="product-info__pic">
                                                    <img src={% static "icons\Group 43.png" %}>
                                                </button>
                                            </a>
                                        {% endif %}
                                    {% else %}
                                        {% if good.id in basket %}
                                            <a href="{% url "cart:cart_add" %}" class="add-to-cart added-to-cart" data-product-id="{{good.id}}">
                                                {% csrf_token %}
                                                <button class="product-info__pic">
                                                    <img src={% static "icons\Group 43.png" %}>
                                                </button>
                                            </a>
                                        {% else %}
                                            <a href="{% url "cart:cart_add" %}" class="add-to-cart" data-product-id="{{good.id}}">
                                                {% csrf_token %}
                                                <button class="product-info__pic">
                                                    <img src={% static "icons\Group 43.png" %}>
                                                </button>
                                            </a>
                                        {% endif %}
                                    {% endif %}
                                    {% if good.id in favourites %}
                                        <a href="{% url "cart:like_add" %}" class="add-to-like added-to-like" data-product-id="{{good.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group.png" %}>
                                            </button>
                                        </a>
                                    {% else %}
                                        <a href="{% url "cart:like_add" %}" class="add-to-like" data-product-id="{{good.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group.png" %}>
                                            </button>
                                        </a>
                                    {% endif %}
                                </div>
                                <div class="product-price">
                                    {% if good.discount %}
                                        <div class="product-price__old">
                                            {{good.price}} ₽
                                            <svg viewBox="0 0 52 5" fill="none" xmlns="http://www.w3.org/2000/svg" class="product-price__line">
                                                <path d="M.88 3.938c16.403-3.917 33.836-3.917 50.238 0" stroke="#F34A57" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"></path>
                                            </svg>
                                        </div>
                                        <div class="product-price__new">
                                            <b>{{good.sell_price}} ₽</b>
                                        </div>
                                    {% else %}
                                        <div class="product-price__old">
                                            <br>
                                        </div>
                                        <div class="product-price__new" style='color: black;'>
                                            <b>{{good.price}} ₽</b>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        
    </section>

    <section class="recommend">
        <div class="recommend__title">
            <h1>Их советуют читатели</h1>
        </div>
        <div class="recommend__block">
            <div class="item">
                <a href="" class="item__link">
                    <div class="item__text">
                        <div class="item__text_author">
                            Джоан Кэтлин Роулинг
                        </div>
                        <div class="item__text_title">
                            <b>Harry Potter and the Philosophers Stone</b>
                        </div>
                        <br>
                        <div class="item__text_comment">
                            Это лучшее издание на английском из всех, что видел. Поначалу смущала мягкая обложка, но потом понял, что напрасно - она не пачкается, приятная на ощупь, да и само оформление не подкачало, словом приятно в руках держать. Текст оригинальный английский, неадаптированный, написано простым языком, читалось легко и непринужденно, конечно, приходилось прибегать к словарю периодически, но куда без этого, для прокачки знаний английского очень помогает. Межстрочный интервал достаточный для того, что бы делать пометки карандашом на незнакомые слова, так что если вздумаешь перечитать со временем, не придется снова бегать за словарем. В общем, покупайте, не пожалеете, подойдет как ребенку, так и взрослым, конечно, цена кусается, но оно того стоит!                        
                        </div>
                    </div>
                    <div class="item__pic">
                        <img src={% static "images\english\Harry Potter.jpg" %}>
                    </div>
                </a>
            </div>
            <div class="item">
                <a href="" class="item__link">
                    <div class="item__text">
                        <div class="item__text_author">
                            Содзи Симада
                        </div>
                        <div class="item__text_title">
                            <b>Токийская головоломка</b>
                        </div>
                        <br>
                        <div class="item__text_comment">
                            Тем кому понравился нашумевший в своё время блистательный роман "Токийский зодиака", - данный роман к прочтению обязателен. Всё тот же азиатский колорит, жестокость, умудренность и саспенс. Оторваться при чтении было невозможно, я большой поклонник подобных интеллектуальных игр и противостояния умов, поэтому этот роман стал для меня настоящим подарком. Оформление серийное, достойное.
                        </div>
                    </div>
                    <div class="item__pic">
                        <img src={% static "images\detective\Токийская головоломка.jpg" %}>
                    </div>
                </a>
            </div>            
        </div>
    </section>
{% endblock %}

goods/templates/goods/new.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\new.css" %}">
{% endblock css %}


{% block content %}
    <section class="panel">
        <ul class="menu">
            <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
                <b>Акции</b>
            </li></a>
            <li class="menu_catalog">
                <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
                <ul class="sub-menu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
                    {% endfor %}
                </ul>
            </li>
            <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
                <b>Что еще почитать?</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:bestsellers" %}"><li class="menu_item">
                <b>Бестселлеры</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:new" %}" style="background-color: #fff59d; color: #000; "><li class="menu_item">
                <b>Новинки</b>
            </li></a>
            <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
                <b>О нас</b>
            </li></a>
        </ul>
    </section>

    <hr>

    <section class="block">
        <div class="products">
            {% for good in new %}
                <div class="card hidden">
                    <div class="product">
                        <a id="product" href="{% url "catalog:product" good.slug %}">
                            <div class="product-photo">
                                {% if good.image %}
                                    <img src={{good.image.url}} alt="{{good.name}}">
                                {% endif %}
                            </div>
                            <div class="product-title">
                                <div class="product-title__head">
                                    <b>{{good.name}}</b>
                                </div>
                                <div class="product-title__author">
                                    {% if good.author_name %}
                                        {{good.author_name}}
                                    {% else %}
                                        <br>
                                    {% endif %}
                                </div>
                            </div>
                        </a>
                        <div class="product-info">
                            <div class="product-info__pic">
                                {% if good.id in basket %}
                                        <a href="{% url "cart:cart_add" %}" class="add-to-cart added-to-cart" data-product-id="{{good.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group 43.png" %}>
                                            </button>
                                        </a>
                                    {% else %}
                                        <a href="{% url "cart:cart_add" %}" class="add-to-cart" data-product-id="{{good.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group 43.png" %}>
                                            </button>
                                        </a>
                                    {% endif %}
                                    {% if good.id in favourites %}
                                    <a href="{% url "cart:like_add" %}" class="add-to-like added-to-like" data-product-id="{{good.id}}">
                                        {% csrf_token %}
                                        <button class="product-info__pic">
                                            <img src={% static "icons\Group.png" %}>
                                        </button>
                                    </a>
                                    {% else %}
                                        <a href="{% url "cart:like_add" %}" class="add-to-like" data-product-id="{{good.id}}">
                                            {% csrf_token %}
                                            <button class="product-info__pic">
                                                <img src={% static "icons\Group.png" %}>
                                            </button>
                                        </a>
                                    {% endif %}
                            </div>
                            <div class="product-price">
                                {% if good.discount %}
                                    <div class="product-price__old">
                                        {{good.price}} ₽
                                        <svg viewBox="0 0 52 5" fill="none" xmlns="http://www.w3.org/2000/svg" class="product-price__line">
                                            <path d="M.88 3.938c16.403-3.917 33.836-3.917 50.238 0" stroke="#F34A57" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" vector-effect="non-scaling-stroke"></path>
                                        </svg>
                                    </div>
                                    <div class="product-price__new">
                                        <b>{{good.sell_price}} ₽</b>
                                    </div>
                                {% else %}
                                    <div class="product-price__old">
                                        <br>
                                    </div>
                                    <div class="product-price__new" style='color: black;'>
                                        <b>{{good.price}} ₽</b>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>      
            {% endfor %}
        </div>
        <div class="navigation">
            <button class="btn" type='button'>Показать еще</button>
        </div>
        <script src= {% static "\new.js" %}></script>
    </section>

{% endblock %}