app/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

from app import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

        ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goods/urls.py
from django.urls import path

from goods import views

app_name = 'goods'

urlpatterns = [
    path('search/', views.catalog, name='search'),
    path('bestsellers/', views.bestsellers, name='bestsellers'),
    path('new/', views.new, name='new'),
    path('<slug:category_slug>/', views.catalog, name='index'),
    # path('product/<int:product_id>/', views.product, name='product'),
    path('product/<slug:product_slug>/', views.product, name='product')
]

main/urls.py
from django.urls import path

from main import views

app_name='main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('sales/', views.sales, name='sales'),
    path('else/', views.else_, name='else'),
    # path('contact/', views.handle_contact_form, name='contact'),  # Обработчик формы обратной связи

]

users/urls.py
from django.urls import path

from users import views

app_name='users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('personality/', views.personality, name='personality'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('my_orders/', views.my_orders, name='my_orders'),
    path('users-cart/', views.users_cart, name='users_cart'),
    path('like/', views.like, name='like'),
]

orders/models.py
from django.db import models
from goods.models import Products

from users.models import User

class OrderitemQueryset(models.QuerySet):
    
    def full_price(self):
        return sum(cart.full_price() for cart in self)
    
    def full_discount(self):
        return sum(cart.full_discount() for cart in self)

    def total_price(self):
        return sum(cart.products_price() for cart in self)


class Order(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя получателя', blank=True, null=True, default=None)
    last_name = models.CharField(max_length=150, verbose_name='Фамилия получателя', blank=True, null=True, default=None)
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name="Пользователь", default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания заказа")
    phone_number = models.CharField(max_length=20, verbose_name="Номер телефона")
    delivery_address = models.TextField(null=True, blank=True, verbose_name="Адрес доставки")
    flat = models.CharField(null=True, blank=True, verbose_name='Квартира или офис')
    comment = models.TextField(null=True, blank=True, verbose_name='Комментарий к заказу')
    is_paid = models.BooleanField(default=False, verbose_name="Оплачено")
    status = models.CharField(max_length=50, default='В обработке', verbose_name="Статус заказа")
    qr_image = models.ImageField(upload_to='qr_codes/', null=True, blank=True, verbose_name="QR-код")  # Новое поле для QR-кода
    tracking_number = models.CharField(null=True, blank=True, verbose_name='Трек-код')

    class Meta:
        db_table = "order"
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        if self.first_name and self.last_name:
            return f"Заказ № {self.pk} | Получатель {self.first_name} {self.last_name}"
        else:
            return f"Заказ № {self.pk} | Получатель {self.user.first_name} {self.user.last_name}"

class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name="Заказ")
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, verbose_name="Продукт", default=None)
    name = models.CharField(max_length=150, verbose_name="Название", default=None)
    author_name = models.CharField(max_length=150, verbose_name='Автор', null=True, blank=True)
    image = models.ImageField(blank=True, null=True, verbose_name='Изображение')
    price = models.DecimalField(max_digits=7, decimal_places=0, verbose_name="Цена", default=0)
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name="Дата продажи")

    class Meta:
        db_table = "order_item"
        verbose_name = "Проданный товар"
        verbose_name_plural = "Проданные товары"

    objects = OrderitemQueryset.as_manager()

    # def full_price(self):
    #     return self.price * self.quantity
    
    # def full_discount(self):
    #     return  round((self.price * self.product.discount // 100), 2) * self.quantity
    
    def products_price(self):
        return round(self.price * self.quantity, 0)

    def __str__(self):
        return f"Товар {self.name} | Заказ № {self.order.pk}"

users/models.py
from re import T
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    phone_number = models.CharField(max_length=20, blank=True, null=True)
    middle_name = models.CharField(max_length=255, blank=True, null=True)

    class Meta:
        db_table = "user"
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User
import phonenumbers

class UserLoginForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']
   
    username = forms.CharField()
    password = forms.CharField()

class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "password1",
            "password2",
            "phone_number"
        )

    def clean_confirmation(self):
        if self.cleaned_data["confirmation"] is not True:
            raise forms.ValidationError("You must confirm!")

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    phone_number = forms.CharField()


class ProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "phone_number",
            'middle_name'
        )

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    phone_number = forms.CharField()
    middle_name = forms.CharField(required=False)

users/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Prefetch
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.contrib import auth, messages
from django.urls import reverse
from goods.models import Categories, Products
from datetime import datetime
from carts.models import Cart, Like
from orders.models import Order, OrderItem
from users.forms import ProfileForm, UserLoginForm, UserRegistrationForm
from main.forms import ContactForm
from django.contrib import messages

from django.core.mail import send_mail

def login(request):
    if request.method == 'POST':
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = auth.authenticate(username=username, password=password, backend='modules.system.backends.EmailAuthBackend')
            session_key = request.session.session_key
            if user:
                auth.login(request, user)
                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                    Like.objects.filter(session_key=session_key).update(user=user)
                redirect_page = request.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(request.POST.get('next'))
                
                return HttpResponseRedirect(reverse('user:profile'))
        else:
            # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
            categories = Categories.objects.all()
            manga = Products.objects.filter(category__slug='Manga').order_by('?')[:6]
            new = Products.objects.filter(year_of_publish=datetime.now().year).order_by('?')[:6]

            context: dict = {
                'form': form,
                'title': 'Chapter & Verse - Главная',
                'categories': categories,
                'manga': manga,
                'new': new
            }
            return render(request, 'main/index.html', context)  # Шаблон, который содержит модальное окно

def registration(request):
    if request.method == 'POST':
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            user = form.save()
            user.phone_number = form.cleaned_data.get('phone_number')           
            user.save()
            user = form.instance
            
            session_key = request.session.session_key
            
            # Авторизуем пользователя
            auth.login(request, user)
            
            if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)
                    Like.objects.filter(session_key=session_key).update(user=user)
            
            return HttpResponseRedirect(reverse('user:profile'))
        else:
            # Возвращаем страницу, которая содержит модальное окно, с контекстом, чтобы показать ошибки
            categories = Categories.objects.all()
            manga = Products.objects.filter(category__slug='Manga').order_by('?')[:6]
            new = Products.objects.filter(year_of_publish=datetime.now().year).order_by('?')[:6]

            context: dict = {
                'form': form,
                'title': 'Chapter & Verse - Главная',
                'categories': categories,
                'manga': manga,
                'new': new
            }
            return render(request, 'main/index.html', context)  # Шаблон, который содержит модальное окно


@login_required
def profile(request):
    form = ProfileForm(instance=request.user)
    modal_form, redirect_anchor = handle_contact_form(request)
    if request.user.is_authenticated:
        basket = [item.product_id for item in Cart.objects.filter(user=request.user)]
        select = Like.objects.filter(user=request.user)[:5]
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        basket = [item.product_id for item in Cart.objects.filter(session_key = request.session.session_key)]
        select = Like.objects.filter(session_key = request.session.session_key)[:5]
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]

    orders = (
        Order.objects.filter(user=request.user).exclude(status__in=['Выполнен', 'Отменен'])
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product")
                )
            )
            .order_by("-id")[:1]
    )

    context = {
        "title": "Chapter & Verse - Профиль", 
        'form': form,
        'select': select,
        'favourites': favourites,
        'basket': basket,
        "orders": orders,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
    }
    return render(request, 'users/profile.html', context)  # Шаблон, который содержит модальное окно

@login_required
def personality(request):
    form = ProfileForm(instance=request.user)
    modal_form = ContactForm()
    redirect_anchor = None

    if request.method == 'POST':
        form_type = request.POST.get('form_type')

        if form_type == 'profile_form':
            form = ProfileForm(data=request.POST, instance=request.user)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('users:personality'))
                   
        elif form_type == 'contact_form':
            modal_form = ContactForm(request.POST)
            redirect_anchor = '#contacts'
            
            if modal_form.is_valid():
                fisrt_name = modal_form.cleaned_data['first_name']
                username = modal_form.cleaned_data['username']
                message = modal_form.cleaned_data['message']
                send_contact_email(fisrt_name, username, message)
                messages.success(request, "Сообщение успешно отправлено!")
            else:
                errors = {field: error for field, error in modal_form.errors.items()}
                messages.error(request, "Ошибка при отправке сообщения")

    context = {
        'title': 'Chapter & Verse - Личные данные',
        'form': form,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
    }
    return render(request, 'users/personality.html', context)

@login_required
def logout(request):
    auth.logout(request)
    return redirect(reverse('main:index'))

@login_required
def my_orders(request):
    form = ProfileForm(instance=request.user)
    modal_form, redirect_anchor = handle_contact_form(request)

    orders = (
            Order.objects.filter(user=request.user).prefetch_related(
                Prefetch(
                    'orderitem_set',
                    queryset=OrderItem.objects.select_related('product')
                )
            ).order_by('-id')
        )

    context = {
        "title": "Chapter & Verse - Мои заказы", 
        'form': form,
        'orders': orders,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
        }
    return render(request, "users/my_orders.html", context)

def users_cart(request):
    modal_form, redirect_anchor = handle_contact_form(request)
    if request.user.is_authenticated:
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]
    
    context = {
        "title": "Chapter & Verse - Корзина", 
        'favourites': favourites,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        }
    return render(request, "users/users_cart.html", context)

def like(request):
    modal_form, redirect_anchor = handle_contact_form(request)
    if request.user.is_authenticated:
        basket = [item.product_id for item in Cart.objects.filter(user=request.user)]
        favourites = [item.product_id for item in Like.objects.filter(user=request.user)]
    else:
        basket = [item.product_id for item in Cart.objects.filter(session_key = request.session.session_key)]
        favourites = [item.product_id for item in Like.objects.filter(session_key = request.session.session_key)]
    
    context = {
        "title": "Chapter & Verse - Избранное",
        'basket': basket, 
        'favourites': favourites,
        'modal_form': modal_form,
        'redirect_anchor': redirect_anchor
        
        }
    return render(request, "users/like.html", context)

def send_contact_email(first_name, username, message):
    subject = "Сообщение с вашего сайта"
    body = f"Сообщение от {first_name} ({username}):\n\n{message}"
    from_email = 'olechka.chumakovachumakova@yandex.ru'  # Адрес электронной почты отправителя
    to_email = 'olechka.chumakovachumakova@yandex.ru'  # Адрес электронной почты, куда придет письмо
    
    send_mail(
        subject,
        body,
        from_email, 
        [to_email], 
        fail_silently=False
    )

def handle_contact_form(request):
    if request.method == 'POST':
        modal_form = ContactForm(request.POST)
        redirect_anchor = '#contacts'
        if modal_form.is_valid():
            fisrt_name = modal_form.cleaned_data['first_name']
            username = modal_form.cleaned_data['username']
            message = modal_form.cleaned_data['message']
            send_contact_email(fisrt_name, username, message)
            messages.success(request, "Сообщение успешно отправлено!")
        else:
            errors = {field: error for field, error in modal_form.errors.items()}
            messages.error(request, "Ошибка при отправке сообщения")
    else:

users/templates/users/like.html
{% extends "base.html" %}
{% load static %}

{% load carts_tags %}
{% load goods_tags %}
{% user_likes request as likes %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\like.css" %}">
{% endblock css %}

{% block content %}
    <section class="panel">
        <ul class="menu">
            <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
                <b>Акции</b>
            </li></a>
            <li class="menu_catalog">
                <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
                <ul class="sub-menu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
                    {% endfor %}
                </ul>
            </li>
            <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
                <b>Что еще почитать?</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:bestsellers" %}"><li class="menu_item">
                <b>Бестселлеры</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:new" %}"><li class="menu_item">
                <b>Новинки</b>
            </li></a>
            <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
                <b>О нас</b>
            </li></a>
        </ul>
    </section>

    <hr>

    <section class="block">
        <div class="catalog">
            <div class="catalog__items">
                <ul>
                    <li><a class="catalog__items_item" href="{% url "user:profile" %}">
                        Профиль
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:personality" %}">
                        Личные данные
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:my_orders" %}">
                        Заказы
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:like" %}" style="color: black">
                        <b>Избранное</b>
                    </a></li>
                    <hr>
                    <li><a class="catalog__items_item" href="{% url "user:logout" %}" style="color: #921A22;">
                        Выйти
                    </a></li>
                </ul>
            </div>
        </div>
        <div class="main">
            <div class="main__title">
                <b>Избранное</b>
            </div>
            <div class="container" id='like-items-container'>
                {% include "carts/includes/included_like.html" %}   
            </div>
        </div> 
    </section>

{% endblock content %}

users/templates/users/my_orders.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% load goods_tags %}
{% load carts_tags %}

{% user_likes request as likes %}
{% user_carts request as carts %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\orders.css" %}">
{% endblock css %}

{% block content %}
    <section class="panel">
        <ul class="menu">
            <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
                <b>Акции</b>
            </li></a>
            <li class="menu_catalog">
                <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
                <ul class="sub-menu">
                    {% tag_categories as categories %}
                    {% for category in categories %}
                        <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
                    {% endfor %}
                </ul>
            </li>
            <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
                <b>Что еще почитать?</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:bestsellers" %}"><li class="menu_item">
                <b>Бестселлеры</b>
            </li></a>
            <a class="menu_link" href="{% url "catalog:new" %}"><li class="menu_item">
                <b>Новинки</b>
            </li></a>
            <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
                <b>О нас</b>
            </li></a>
        </ul>
    </section>

    <hr>

    <section class="block">
        <div class="catalog">
            <div class="catalog__items">
                <ul>
                    <li><a class="catalog__items_item" href="{% url "user:profile" %}">
                        Профиль
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:personality" %}">
                        Личные данные
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:my_orders" %}" style="color: black">
                       <b>Заказы</b>
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:like" %}">
                        Избранное
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <hr>
                    <li><a class="catalog__items_item" href="{% url "user:logout" %}" style="color: #921A22;">
                        Выйти
                    </a></li>
                </ul>
            </div>
        </div>
        <div class="main">
            <div class="main__title">
                <b>Заказы</b>
            </div>
            {% for order in orders %}
                <div class="main__item">
                    <div class="main__item_title">
                        <div class="main__item_title-order">
                            <b>Заказ №{{order.id}} от {{order.created_timestamp}}</b>
                            {% if order.status == 'Отправлен' %}
                                <p style='font-size: 14px; margin-left: 15px; color: #7e7e7e'>Ваш номер для отслеживания: {{order.tracking_number}}</p>
                            {% endif %}
                        </div>
                        <div class="main__item_title-status" style="{% if order.status == 'В обработке' or order.status == 'Отправлен' or order.status == 'В сборке' %}
                                                                        background-color: #fff59d;
                                                                    {% elif order.status == 'Выполнен' %}
                                                                        background-color: #dedede;
                                                                    {% elif order.status == 'Отменен' %}
                                                                        background-color: #ffcc80;
                                                                    {% endif %}">
                            {{order.status}}
                        </div>
                    </div>
                    <div class="main__item_products">
                        <div class="main__item_products-good">
                            <ul class="products clearfix orders">
                                {% for item in order.orderitem_set.all %}
                                    <li class="product-wrapper orders__item">
                                        <div class="product">
                                            {% if item.image %}
                                                <img src={{item.image.url}} alt="{{item.name}}">
                                            {% endif %}                                        
                                        </div>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                        <div class="main__item_products-sum">
                            <b>{{order.orderitem_set.total_price}} ₽</b>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </section>

{% endblock %}

users/templates/users/personality.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}
{% load goods_tags %}

{% block css %}
    <link rel="stylesheet" href="{% static "styles\personal data.css" %}">
{% endblock css %}

{% block content %}
    <section class="panel">
    <ul class="menu">
    <a class="menu_link" href="{% url "main:sales" %}"><li class="menu_item">
        <b>Акции</b>
    </li></a>
    <li class="menu_catalog">
        <a class="main-item" href="javascript:void(0);"><b>Каталог</b></a>
        <ul class="sub-menu">
            {% tag_categories as categories %}
            {% for category in categories %}
                <li><a class="menu_link__item" href="{% url "catalog:index" category.slug%}"><b>{{category.name}}</b></a></li>
            {% endfor %}
        </ul>
    </li>
    <a class="menu_link" href="{% url "main:else" %}"><li class="menu_item">
        <b>Что еще почитать?</b>
    </li></a>
    <a class="menu_link" href="{% url "catalog:bestsellers" %}"><li class="menu_item">
        <b>Бестселлеры</b>
    </li></a>
    <a class="menu_link" href="{% url "catalog:new" %}"><li class="menu_item">
        <b>Новинки</b>
    </li></a>
    <a class="menu_link" href="{% url "main:about" %}"><li class="menu_item">
        <b>О нас</b>
    </li></a>
    </ul>
    </section>

    <hr>

    <section class="block">
        <div class="catalog">
            <div class="catalog__items">
                <ul>
                    <li><a class="catalog__items_item" href="{% url "user:profile" %}">
                        Профиль
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:personality" %}" style="color: black">
                        <b>Личные данные</b>
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:my_orders" %}">
                        Заказы
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <li><a class="catalog__items_item" href="{% url "user:like" %}">
                        Избранное
                        <img src="{% static "icons\Vector 12.png" %}">
                    </a></li>
                    <hr>
                    <li><a class="catalog__items_item" href="{% url "user:logout" %}" style="color: #921A22;">
                        Выйти
                    </a></li>
                </ul>
            </div>
        </div>

        <div class="main">
            <div class="main__title">
                <b>Личные данные</b>
            </div>
            <form action="{% url "users:personality" %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="form_type" value="profile_form">
                <div class="main__item">
                    <div class="main__item_inputContainer">
                        <input class="main__item_inputContainer-txt" inputmode="kana-name" placeholder="*Имя" required 
                        type="name" value="{{form.first_name.value}}" name="first_name" id='id_first_name'>
                        {% if form.first_name.errors %}
                        <div class="alert-danger">
                            {{form.first_name.errors}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="main__item_inputContainer">
                        <input class="main__item_inputContainer-txt" inputmode="surname" placeholder="*Фамилия" required type="surname" value="{{form.last_name.value}}" name="last_name" id='id_last_name'>
                        {% if form.last_name.errors %}
                        <div class="alert-danger">
                            {{form.last_name.errors}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="main__item_inputContainer">
                        <input class="main__item_inputContainer-txt" placeholder="Отчество" type="patronym" value="{% if form.middle_name.value %}{{form.middle_name.value}}{% endif %}" name="middle_name" tag="patronym" id='id_middle_name'>
                        {% if form.middle_name.errors %}
                        <div class="alert-danger">
                            {{form.middle_name.errors}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="main__item_inputContainer">
                        <input class="main__item_inputContainer-txt" placeholder="*Телефон" required type="tel" value="{{form.phone_number.value|phone_format}}" name="phone_number" id='id_phone_number'>
                        {% if form.phone_number.errors %}
                        <div class="alert-danger">
                            {{form.phone_number.errors}}
                        </div>
                        {% endif %}
                    </div>
                    <div class="main__item_inputContainer">
                        <input class="main__item_inputContainer-txt" placeholder="*email" required type="email" value="{{form.username.value}}" name="username" id='id_username'>
                        {% if form.username.errors %}
                        <div class="alert-danger">
                            {{form.username.errors}}
                        </div>
                        {% endif %}
                    </div>
                </div>
                <div class="main__btn">
                    <button type='submit' class="main__btn_btn">Сохранить изменения</button>
                </div>
            </form>
        </div>
    </section>

{% endblock %}